# Generated by Django 6.0.8 on 2026-09-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0016_aiexecutionrecord_task_name_and_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='source_file',
            field=models.FileField(blank=True, help_text='文件模式上传的原始 Excel 文档，用于下载', null=True, upload_to='ui-automation/ai-source-files/', verbose_name='原始用例文档'),
        ),
    ]
