# Generated by Django 6.0.7 on 2026-08-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='l1',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='L1'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='l2',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='L2'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='l3',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='L3'),
        ),
    ]
