# Generated by Django 6.0.8 on 2026-09-11 06:54

import apps.testcases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0006_testcase_case_type_multi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='case_type',
            field=models.JSONField(default=apps.testcases.models.default_case_types, verbose_name='用例类型'),
        ),
    ]
