# Generated by Django 6.0.8 on 2026-08-06 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('text', '纯文本')], default='markdown', max_length=20, verbose_name='模板类型')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='邮件主题')),
                ('content', models.TextField(help_text='支持 {{变量}} 替换', verbose_name='模板内容')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='模板变量')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知模板',
                'verbose_name_plural': '通知模板',
                'db_table': 'notification_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('total_requests', models.IntegerField(default=0, verbose_name='总请求数')),
                ('avg_response_time', models.FloatField(default=0, verbose_name='平均响应时间(ms)')),
                ('max_response_time', models.FloatField(default=0, verbose_name='最大响应时间(ms)')),
                ('min_response_time', models.FloatField(default=0, verbose_name='最小响应时间(ms)')),
                ('error_count', models.IntegerField(default=0, verbose_name='错误请求数')),
                ('slow_requests', models.IntegerField(default=0, verbose_name='慢请求数(>1s)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '性能统计',
                'verbose_name_plural': '性能统计',
                'db_table': 'performance_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='email_attach_report',
            field=models.BooleanField(default=False, verbose_name='邮件附件报告'),
        ),
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='email_recipients',
            field=models.JSONField(blank=True, default=list, help_text='用户ID或邮箱地址列表', verbose_name='邮件收件人'),
        ),
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='notification_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_configs', to='core.notificationtemplate', verbose_name='通知模板'),
        ),
        migrations.CreateModel(
            name='RequestPerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, verbose_name='请求路径')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('response_time', models.FloatField(verbose_name='响应时间(ms)')),
                ('status_code', models.IntegerField(verbose_name='状态码')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '请求性能日志',
                'verbose_name_plural': '请求性能日志',
                'db_table': 'request_performance_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path'], name='request_per_path_4ef13f_idx'), models.Index(fields=['status_code'], name='request_per_status__d78e82_idx'), models.Index(fields=['-response_time'], name='request_per_respons_fd9ee7_idx'), models.Index(fields=['-created_at'], name='request_per_created_0d64c2_idx')],
            },
        ),
    ]
