# Generated by Django 6.0.8 on 2026-09-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_repair_notification_and_perf_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiednotificationconfig',
            name='config_type',
            field=models.CharField(choices=[('webhook_feishu', '飞书机器人')], default='webhook_feishu', max_length=20, verbose_name='配置类型'),
        ),
        migrations.AlterField(
            model_name='unifiednotificationconfig',
            name='webhook_bots',
            field=models.JSONField(blank=True, default=dict, help_text='飞书机器人配置', null=True, verbose_name='Webhook机器人配置'),
        ),
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认邮箱配置', max_length=100, verbose_name='配置名称')),
                ('smtp_host', models.CharField(blank=True, help_text='如 smtp.qq.com / smtp.163.com', max_length=255, verbose_name='SMTP服务器')),
                ('smtp_port', models.PositiveIntegerField(default=465, help_text='SSL 通常为 465，TLS/STARTTLS 通常为 587', verbose_name='SMTP端口')),
                ('sender_email', models.CharField(blank=True, max_length=255, verbose_name='发件人邮箱')),
                ('smtp_password', models.CharField(blank=True, help_text='邮箱 SMTP 授权码（非登录密码）', max_length=255, verbose_name='授权码')),
                ('use_ssl', models.BooleanField(default=True, verbose_name='使用SSL')),
                ('use_tls', models.BooleanField(default=False, verbose_name='使用TLS')),
                ('recipient_emails', models.JSONField(blank=True, default=list, help_text='定时任务「通知邮箱」下拉的候选邮箱列表', verbose_name='通知收件人')),
                ('is_active', models.BooleanField(default=True, help_text='关闭后发送逻辑回退到 settings 中的 EMAIL_* 配置', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邮箱配置',
                'verbose_name_plural': '邮箱配置',
                'db_table': 'core_email_configs',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['is_active'], name='core_email__is_acti_8ef33e_idx')],
            },
        ),
    ]
