# Generated by Django 6.0.8 on 2026-08-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasestep',
            name='page_filter',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='页面筛选'),
        ),
        migrations.AlterField(
            model_name='scriptstep',
            name='action_type',
            field=models.CharField(choices=[('CLICK', '点击'), ('INPUT', '输入'), ('SELECT', '选择'), ('VERIFY', '验证'), ('WAIT', '等待'), ('HOVER', '悬停'), ('SCROLL', '滚动'), ('NAVIGATE', '跳转URL'), ('SCREENSHOT', '截图'), ('SWITCH_TAB', '切换标签页'), ('CUSTOM', '自定义')], max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='testcasestep',
            name='action_type',
            field=models.CharField(choices=[('click', '点击'), ('fill', '输入文本'), ('getText', '获取文本'), ('waitFor', '等待元素'), ('hover', '悬停'), ('scroll', '滚动'), ('screenshot', '截图'), ('assert', '断言'), ('wait', '等待'), ('switchTab', '切换标签页'), ('navigateUrl', '跳转URL')], max_length=20, verbose_name='操作类型'),
        ),
    ]
