# Generated by Django 6.0.8 on 2026-09-06 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0012_add_figma_source_type'),
        ('ui_automation', '0012_ensure_aiexploration_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexplorationtask',
            name='ai_model_config',
            field=models.ForeignKey(blank=True, help_text='关联AI智能模式配置的模型', null=True, on_delete=django.db.models.deletion.SET_NULL, to='requirement_analysis.aimodelconfig', verbose_name='AI模型配置'),
        ),
        migrations.AlterField(
            model_name='testcasestep',
            name='assert_type',
            field=models.CharField(blank=True, choices=[('textContains', '文本包含'), ('textEquals', '文本等于'), ('isVisible', '元素可见'), ('exists', '元素存在'), ('hasAttribute', '属性值'), ('urlContains', 'URL包含')], max_length=20, verbose_name='断言类型'),
        ),
    ]
