# Generated by Django 6.0.8 on 2026-09-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0014_exploration_generated_code_and_locator_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='parsed_cases',
            field=models.JSONField(default=list, help_text='文件模式上传解析的用例结构，用于详情页还原用例明细', verbose_name='解析用例树'),
        ),
    ]
