# Generated by Django 6.0.8 on 2026-09-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0015_aiexecutionrecord_parsed_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='task_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='任务名称'),
        ),
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='task_source',
            field=models.CharField(choices=[('text', '文本描述'), ('file', '用例文档')], default='text', max_length=20, verbose_name='任务来源'),
        ),
    ]
