# Generated by Django 6.0.8 on 2026-09-11 06:54

import django.db.models.deletion
from django.db import migrations, models


def backfill_hub_testcase_links(apps, schema_editor):
    """把历史「{标题}-AI生成步骤」用例绑到主平台用例，保证重复生成走更新。"""
    UiTestCase = apps.get_model('ui_automation', 'TestCase')
    UiProject = apps.get_model('ui_automation', 'UiProject')
    HubTestCase = apps.get_model('testcases', 'TestCase')

    suffix = '-AI生成步骤'
    for ui_case in UiTestCase.objects.filter(name__endswith=suffix).iterator():
        if ui_case.hub_testcase_id:
            continue
        base_title = ui_case.name[: -len(suffix)]
        ui_project = UiProject.objects.filter(pk=ui_case.project_id).first()
        if not ui_project or not ui_project.hub_project_id:
            continue

        title_candidates = []
        for t in (base_title, base_title.rstrip('-').rstrip()):
            if t and t not in title_candidates:
                title_candidates.append(t)

        hub = None
        for title in title_candidates:
            hub = HubTestCase.objects.filter(
                project_id=ui_project.hub_project_id,
                title=title,
            ).order_by('id').first()
            if hub:
                break

        if not hub:
            # 标题曾微调：按「UI 名称以 hub.title 开头」反查
            for h in HubTestCase.objects.filter(
                project_id=ui_project.hub_project_id
            ).order_by('id'):
                if not h.title:
                    continue
                if ui_case.name == f'{h.title}{suffix}' or ui_case.name.startswith(h.title):
                    if UiTestCase.objects.filter(hub_testcase_id=h.id).exclude(pk=ui_case.pk).exists():
                        continue
                    hub = h
                    break

        if not hub:
            continue
        if UiTestCase.objects.filter(hub_testcase_id=hub.id).exclude(pk=ui_case.pk).exists():
            continue
        ui_case.hub_testcase_id = hub.id
        ui_case.save(update_fields=['hub_testcase_id'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0012_add_figma_source_type'),
        ('testcases', '0007_testcase_hub_testcase'),
        ('ui_automation', '0018_alter_aiexecutionrecord_task_source_case_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='hub_testcase',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ui_automation_case',
                to='testcases.testcase',
                verbose_name='关联主平台用例',
            ),
        ),
        migrations.RunPython(backfill_hub_testcase_links, noop_reverse),
        migrations.AlterField(
            model_name='aiexecutionrecord',
            name='task_source',
            field=models.CharField(
                choices=[
                    ('text', '文本描述'),
                    ('file', '用例文档'),
                    ('case_conversion', '用例转换'),
                ],
                default='text',
                max_length=20,
                verbose_name='任务来源',
            ),
        ),
        migrations.AlterField(
            model_name='aiexplorationtask',
            name='ai_model_config',
            field=models.ForeignKey(
                blank=True,
                help_text='关联模型配置的模型',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='requirement_analysis.aimodelconfig',
                verbose_name='AI模型配置',
            ),
        ),
    ]
