# Generated by Django 6.0.8 on 2026-08-06 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_notificationtemplate_performancestatistics_and_more'),
        ('django_q', '0019_alter_task_options_alter_ormq_key_alter_ormq_lock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('API', 'API测试'), ('UI', 'UI自动化'), ('APP', 'APP自动化')], max_length=20, verbose_name='所属模块')),
                ('task_type', models.CharField(choices=[('API_TEST_SUITE', 'API测试套件'), ('API_REQUEST', 'API请求'), ('UI_TEST_SUITE', 'UI测试套件'), ('UI_TEST_CASE', 'UI测试用例'), ('APP_TEST_SUITE', 'APP测试套件'), ('APP_TEST_CASE', 'APP测试用例')], max_length=30, verbose_name='任务类型')),
                ('project_id', models.IntegerField(blank=True, null=True, verbose_name='项目ID')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='目标ID')),
                ('environment_id', models.IntegerField(blank=True, null=True, verbose_name='环境ID')),
                ('task_config', models.JSONField(blank=True, default=dict, verbose_name='任务配置')),
                ('status', models.CharField(choices=[('ACTIVE', '活跃'), ('PAUSED', '已暂停')], default='ACTIVE', max_length=10, verbose_name='状态')),
                ('notify_on_success', models.BooleanField(default=False, verbose_name='成功时通知')),
                ('notify_on_failure', models.BooleanField(default=True, verbose_name='失败时通知')),
                ('notify_on_email', models.BooleanField(default=False, verbose_name='邮件通知')),
                ('notify_on_webhook', models.BooleanField(default=False, verbose_name='Webhook通知')),
                ('last_run_time', models.DateTimeField(blank=True, null=True, verbose_name='最后运行时间')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功次数')),
                ('failure_count', models.IntegerField(default=0, verbose_name='失败次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notification_configs', models.ManyToManyField(blank=True, to='core.unifiednotificationconfig', verbose_name='通知配置')),
                ('notification_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_configs', to='core.notificationtemplate', verbose_name='通知模板')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='django_q.schedule', verbose_name='Django-Q调度任务')),
            ],
            options={
                'verbose_name': '定时任务调度配置',
                'verbose_name_plural': '定时任务调度配置',
                'db_table': 'scheduler_schedule_config',
                'ordering': ['-created_at'],
            },
        ),
    ]
