# Generated by Django 6.0.8 on 2026-08-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notificationtemplate_performancestatistics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='description',
            field=models.TextField(blank=True, help_text='对该模板用途的简要描述', verbose_name='模板描述'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='content',
            field=models.TextField(help_text='支持 {{变量}} 替换。可用变量：{{task_name}}、{{status_text}}、{{execution_time}}、{{task_type}}、{{title}}、{{tester}}、{{total_cases}}、{{passed_cases}}、{{failed_cases}}、{{error_cases}}、{{skipped_cases}}、{{runtime}}、{{begin_time}}', verbose_name='模板内容'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(blank=True, help_text='邮件通知使用的主题，支持 {{变量}} 替换', max_length=200, verbose_name='邮件主题'),
        ),
    ]
