# Generated by Django 6.0.8 on 2026-09-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_module_switch'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mcpserver',
            new_name='core_mcp_se_is_enab_982cda_idx',
            old_name='core_mcp_se_is_enab_idx',
        ),
        migrations.RenameIndex(
            model_name='mcpserver',
            new_name='core_mcp_se_connect_62d30e_idx',
            old_name='core_mcp_se_connect_idx',
        ),
        migrations.RenameIndex(
            model_name='moduleswitch',
            new_name='core_module_is_enab_353a71_idx',
            old_name='core_module__is_enab_6e5f4e_idx',
        ),
        migrations.RenameIndex(
            model_name='moduleswitch',
            new_name='core_module_locatio_2eee36_idx',
            old_name='core_module__locatio_5bf6a7_idx',
        ),
        migrations.RenameIndex(
            model_name='skill',
            new_name='core_skills_is_enab_3164db_idx',
            old_name='core_skills_is_enab_7f2a1c_idx',
        ),
        migrations.RenameIndex(
            model_name='skill',
            new_name='core_skills_is_buil_a668fa_idx',
            old_name='core_skills_is_buil_9c4e2d_idx',
        ),
    ]
