# Generated by Django 6.0.8 on 2026-08-31 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0002_initial'),
        ('versions', '0004_version_owner_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='testruncasehistory',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_case_histories', to='versions.version', verbose_name='关联版本'),
        ),
    ]
