# Generated by Django 6.0.8 on 2026-09-15 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0013_repair_source_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelconfig',
            name='scenario',
            field=models.CharField(choices=[('testcase_generation', '测试用例生成'), ('ui_automation', 'UI 自动化测试'), ('api_testing', '接口测试'), ('code_generation', '代码生成'), ('other', '其他')], default='testcase_generation', max_length=30, verbose_name='用途场景'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='role',
            field=models.CharField(choices=[('writer', '测试用例编写专家'), ('reviewer', '测试评审专家'), ('browser_use_text', 'Browser Use - 文本模式'), ('browser_use_vision', 'Browser Use - 视觉模式'), ('code_generator', '代码生成专家'), ('test_oracle', '测试预言专家')], max_length=30, verbose_name='角色'),
        ),
        migrations.AddIndex(
            model_name='aimodelconfig',
            index=models.Index(fields=['scenario', 'is_active'], name='ai_model_co_scenari_1ae966_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodelconfig',
            index=models.Index(fields=['model_type', 'is_active'], name='ai_model_co_model_t_74367a_idx'),
        ),
    ]
