# Generated by Django 6.0.7 on 2026-08-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('in_progress', '进行中'), ('released', '已发布'), ('deprecated', '已废弃')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
